/*
CREATE TABLE IF NOT EXISTS projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done boolean,
    projectid integer REFERENCES projects(id)
);

INSERT INTO projects (name, priority, description, deliverydate)
    VALUES ('Make a Wepp App', 1, 'Using javascript', '2019-05-12');

INSERT INTO projects (name, priority, description, deliverydate)
    VALUES ('Make a Mobile App', 1, 'Using java', '2019-05-11');

INSERT INTO projects (name, priority, description, deliverydate)
    VALUES ('Make a Desktop App', 1, 'Using c++', '2019-05-10');


INSERT INTO tasks(name, done, projectid)
    VALUES('download Vue', false, 1);

INSERT INTO tasks(name, done, projectid)
    VALUES('code full', false, 1);
*/